#!/usr/bin/env python3

import sys

from riptide_rqt_plugins.controllers import ControllersPlugin
from rqt_gui.main import Main

plugin = 'riptide_rqt_plugins'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))